# Generated by Django 5.0.1 on 2024-02-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0009_cartinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
