# Generated by Django 5.0.1 on 2024-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0010_alter_cartinfo_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='getinfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pluss', models.IntegerField()),
                ('minuss', models.IntegerField()),
            ],
        ),
    ]
