# Generated by Django 5.0.1 on 2024-02-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0011_getinfos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartinfo',
        ),
    ]
