# Generated by Django 5.0.1 on 2024-02-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0012_delete_cartinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('pimage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
