# Generated by Django 5.0.1 on 2024-02-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0013_cartinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartinfo',
        ),
    ]
