# Generated by Django 5.0.1 on 2024-02-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0015_cartinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartinfo',
            name='pquantity',
            field=models.CharField(default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='cartinfo',
            name='ptotalprice',
            field=models.CharField(default=50, max_length=10),
        ),
    ]
