# Generated by Django 5.0.1 on 2024-03-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0016_alter_cartinfo_pquantity_alter_cartinfo_ptotalprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='getinfos',
        ),
    ]
